# Generated by Django 4.2.5 on 2023-10-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quejas',
            fields=[
                ('idQueja', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=30)),
                ('quejaText', models.CharField(max_length=500)),
            ],
        ),
    ]
